server:
  port: 8180

spring:
  datasource:
    url: jdbc:h2:file:./database
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect